### ISSUE TITLE
`assert_matches` with `Vec` types

### ISSUE THREAD

**Issue by nixpulvis** [SimonSapin/rust-std-candidates#18]
It would be great if there was a way to `assert_matches!(&command, Command::Compound([_]));` Where in this case `Command::Compound` contains a single `Vec`.

**Comment by SimonSapin** [comment]
This crate only contains a macro that expands to (roughly) `match $expr { $pattern => true, _ => false }`. What you’re asking for requires changes in the language itself, such as `Deref` in patterns. Consider discussing this in https://internals.rust-lang.org/ (and maybe eventually open a Rust RFC).

Closing as nothing for this can be done in this crate.
