### ISSUE TITLE
Deprecation warning for users of the matches crate following the stabilization of `std::matches`

### ISSUE THREAD

**Issue by bstrie** [SimonSapin/rust-std-candidates#21]
It looks like `std::matches` is on track to be stabilized in Rust 1.42, so I'm interested in discussing whether the matches crate ought to aid users in informing them about the new addition, thereby allowing them to potentially remove the dependency outright. However, for the sake of users on older versions of Rust, I'd say that such a version bump ought to be a breaking change. How would you feel about a 2.0 release that re-exports `std::matches` but adds a deprecation warning? (This is all assuming that #[deprecated] even works on macros...). In addition to changing the README, this would lead to a crates.io page that clearly marks the crate as deprecated, while also informing users who manually update to 2.0 via a deprecation warning, and all the while keeping things working as usual for users on old Rust versions.

An alternative would be to release a minor 1.9 version that merely adds in the deprecation warning without re-exporting `std::matches`, which would require users on old Rust versions to either silence the deprecation warning or to manually pin to an older version of this crate.

Conceivably, we could also do the 2.0 plan soon after `std::matches` is stabilized, and then do the 1.9 plan sometime far when it is safe to assume that 1.42 is a sufficient MSRV, and that the only people who would then be notified are people who never ever bother to manually update the major versions of their dependencies.

**Comment by SimonSapin** [comment]
I think I’m inclined not to do either.

The current version of https://crates.io/crates/matches is 0.1.8. It seems that making 0.2.0 with a deprecation warning would achieve very little: existing users would not see the warning. New users who somehow find this crate but don’t realize the standard library has the same macro seems like a very niche scenario.

As to warning in 0.1.9, I feel it creates busy work for rather little benefit. `matches-0.1.8.crate` is a 2216 bytes download.

I don’t mind changing the readme or doc-comments, though.

**Comment by matthiasbeyer** [comment]
That sounds right for me (I'm the author of [is-match](https://crates.io/crates/is-match), a similar crate).

I'd do the same.
