### ISSUE TITLE
matches 0.1.9 from crates.io contains file that is not in the git repo

### ISSUE THREAD

**Issue by ericseppanen** [SimonSapin/rust-std-candidates#24]
While doing research around the crates.io published crates, I happened to notice that the `matches 0.1.9` tarball, as downloaded from crates.io, contains one additional file (`use_star.rs`). That file does not appear in the this git repo.
```text
$ ls -R
.:
Cargo.toml  Cargo.toml.orig  lib.rs  LICENSE  tests

./tests:
macro_use_one.rs  use_star.rs
```

I'm guessing this is an innocent mistake while using `cargo publish --allow-dirty`.

**Comment by SimonSapin** [comment]
It looks like I wrote a test case for https://github.com/SimonSapin/rust-std-candidates/issues/22 and didn’t commit it, and later published a new version. I’ll add the file to the repo.
